#
# Makefile for testing restart option of docker-compose
#
usage:
	@echo "usage: make [compose]"

compose:
	@echo "> make (compose) [up|down|ps]"
compose-up cu:
	docker-compose up -d -t 0
compose-down cd:
	docker-compose down
compose-ps cp:
	docker-compose ps


