version: "2"

services:
    app:
        image: golang:1.13.1-alpine
        volumes:
            - .:/go/src/example02
        working_dir: /go/src/example02
        command: GO111MODULE=on go run main.go
        links:
            - redis
        environment:
            GO111MODULE: "on"

    redis:
        image: redis:alpine
