version: '3.4'

services:
    app:
        build:
            context: ./
            target: env
            volumes:
                - ./app:/app # Mount source code inside the container.
            command: ["go", "run", "main.go"]
            ports:
                - "2345:2345" # Expose Delve debugger port.
            security_opt:
                - "seccomp:unconfined" # Extra option to allow debugging.
            cap_add:
                - SYS_PTRACE # Recommended option for debugging only.


